### ISSUE TITLE
Needed html commented blocks are removed

### ISSUE THREAD

**Issue by jpruiz114** [stevemao/gulp-remove-html-comments#1]
The library works fine but there should be ways to handle exceptions.

For instance:

```
<!--[if lte IE 8]>
<script src="dist/js/ie/respond.min.js"></script>
<![endif]-->
```
That's a conditional html comment for Internet Explorer. That shouldn't be removed.

Thanks.

**Comment by stevemao** [comment]
see https://github.com/stevemao/remove-html-comments/issues/1 :)
